### ISSUE TITLE
Breaks cmd-click

### ISSUE THREAD

**Issue by dpmccabe** [panzi/intercept-youtube-links#1]
On Chrome (OS X), using Cmd-click on a YouTube link should open the page in a background tab, but this extension instead loads the page in the current tab (without the interstitial). Otherwise, this extension works great.

**Comment by panzi** [comment]
I don't use OS X so I don't know exactly what I have to react to there. Could you please click on the "CLICK HERE" text the way you are usually opening a new tab here and tell me the output: http://fiddle.jshell.net/q8ny4gh5/show/

Thanks!

**Comment by dpmccabe** [comment]
which: 1
meta:  true
ctrl:  false
alt:   false
shift: false

**Comment by panzi** [comment]
Ok, it should be fixed in the new release (in commit f60f87fae84bb25087f1943f89f1d20f513eedb0 in particular). I really forgot to handle _any_ modifier keys. Can you confirm?

**Comment by dpmccabe** [comment]
Confirmed as working. Thanks for the quick turnaround.

**Comment by panzi** [comment]
Great!
